package pedidos;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis David Saenz Jurado Universidad Internacional de la Rioja
 * Plataformas de desarrollo de software 6/12/2020
 */

public class interfazPrincipal extends javax.swing.JFrame {

    //Codigo para borrar campos del formularios
    public void limpiarFormulario() {
        nombreMedicamento.setText("");
        tipoMedicamento.setSelectedIndex(0);
        cantidadProducto.setText("");
        distribuidoresBtns.clearSelection();
        chkPrincipal.setSelected(false);
        chkSecundario.setSelected(false);
    }

    /**
     * Creates new form interfazPrincipal
     */
    public interfazPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        distribuidoresBtns = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        nombreMedicamento = new javax.swing.JTextField();
        tipoMedicamento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantidadProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        borrarCampos = new javax.swing.JButton();
        confirmarPedido = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        distribCofarma = new javax.swing.JRadioButton();
        distribEmpsephar = new javax.swing.JRadioButton();
        distribCemefar = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        chkPrincipal = new javax.swing.JCheckBox();
        chkSecundario = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Solicitar pedido de medicamentos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nombreMedicamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreMedicamento.setToolTipText("Ingresa el nombre del medicamento");
        nombreMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMedicamentoActionPerformed(evt);
            }
        });
        nombreMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreMedicamentoKeyPressed(evt);
            }
        });

        tipoMedicamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipoMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibiótico" }));
        tipoMedicamento.setToolTipText("Selecciona el tipo de medicamento");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del medicamento:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tipo del medicamento:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad de producto:");

        cantidadProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cantidadProducto.setToolTipText("Ingresa la cantidad del producto a solicitar");
        cantidadProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadProductoKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Distribuidor:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Sucursal:");

        borrarCampos.setText("Borrar campos");
        borrarCampos.setToolTipText("Retorna los campos a su valor original");
        borrarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarCamposActionPerformed(evt);
            }
        });

        confirmarPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmarPedido.setText("Confirmar");
        confirmarPedido.setToolTipText("Confirmar y revisar pedido");
        confirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarPedidoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        distribuidoresBtns.add(distribCofarma);
        distribCofarma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        distribCofarma.setText("Cofarma");
        distribCofarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distribCofarmaActionPerformed(evt);
            }
        });

        distribuidoresBtns.add(distribEmpsephar);
        distribEmpsephar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        distribEmpsephar.setText("Empsephar");
        distribEmpsephar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distribEmpsepharActionPerformed(evt);
            }
        });

        distribuidoresBtns.add(distribCemefar);
        distribCemefar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        distribCemefar.setText("Cemefar");
        distribCemefar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distribCemefarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(distribCemefar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distribEmpsephar)
                    .addComponent(distribCofarma, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(distribCofarma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(distribEmpsephar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(distribCemefar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        chkPrincipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkPrincipal.setText("Principal");

        chkSecundario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkSecundario.setText("Secundaria");
        chkSecundario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSecundarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addComponent(chkSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPrincipal)
                    .addComponent(chkSecundario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Salir");
        jButton1.setToolTipText("Cierra la aplicación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(confirmarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(borrarCampos)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cantidadProducto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(nombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarCampos)
                    .addComponent(confirmarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void distribCemefarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distribCemefarActionPerformed

    }//GEN-LAST:event_distribCemefarActionPerformed

    private void confirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarPedidoActionPerformed
        //Crear un nuevo objeto tipo confirmacionPedido
        confirmacionPedido ventana2 = new confirmacionPedido();
        //Obtener texto, tipo y cantidad del medicament
        ventana2.textoMedicamento = nombreMedicamento.getText();
        ventana2.textoTipo = tipoMedicamento.getSelectedItem().toString();
        ventana2.textoCantidad = cantidadProducto.getText();

        //Radio butttons distribuidor
        ventana2.textoDistribuidor = "";
        if (distribCofarma.isSelected()) {
            ventana2.textoDistribuidor = "Cofarma";
        } else {
            if (distribEmpsephar.isSelected()) {
                ventana2.textoDistribuidor = "Empsephar";
            } else {
                if (distribCemefar.isSelected()) {
                    ventana2.textoDistribuidor = "Cemefar";
                }
            }
        }
        //Check boxes
        ventana2.textoSucursal = "";
        if (chkPrincipal.isSelected() == true) {
            ventana2.textoSucursal = "Calle de la Rosa n.28";
        }
        if (chkSecundario.isSelected() == true) {
            ventana2.textoSucursal = "Calle Alcazabilla n. 3";
        }
        if (chkPrincipal.isSelected() == true && chkSecundario.isSelected() == true) {
            ventana2.textoSucursal = "Calle de la Rosa n.28 y para la situada en Calle Alcazabilla n. 3";
        }

        if (chkPrincipal.isSelected() && !chkSecundario.isSelected()) {
            ventana2.direccion = "Pedido al distribuidor Principal";
        } else if (!chkPrincipal.isSelected() && chkSecundario.isSelected()) {
            ventana2.direccion = "Pedido al distribuidor Secundario";
        } else {
            ventana2.direccion = "Pedido al distribuidor Principal y secundario";
        }

        boolean verificacion = true;
        //Verificacion de datos
        if (ventana2.textoMedicamento.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El nombre del medicamento no puede estar vacio");
            verificacion = false;
        }
        if (ventana2.textoCantidad.isEmpty()) {
            JOptionPane.showMessageDialog(null, "La cantididad de producto no puede estar vacia");
            verificacion = false;
        }
        if (Integer.parseInt(ventana2.textoCantidad) == 0) {
            JOptionPane.showMessageDialog(null, "La cantididad debe ser positiva");
            verificacion = false;
        }
        if (ventana2.textoDistribuidor.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tienes que seleccionar un distribuidor");
            verificacion = false;
        }
        if (ventana2.textoSucursal.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tienes que seleccionar una sucursal");
            verificacion = false;
        }

        //Mostrar ventana 2 y ocultar ventana 1
        if (verificacion == true) {
            ventana2.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_confirmarPedidoActionPerformed

    private void borrarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarCamposActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_borrarCamposActionPerformed

    private void nombreMedicamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreMedicamentoKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            nombreMedicamento.setEditable(true);
        } else {
            nombreMedicamento.setEditable(false);
        }
    }//GEN-LAST:event_nombreMedicamentoKeyPressed

    private void cantidadProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadProductoKeyPressed
        // TODO add your handling code here:
        char d = evt.getKeyChar();
        if (Character.isDigit(d) || Character.isISOControl(d)) {
            cantidadProducto.setEditable(true);
        } else {
            cantidadProducto.setEditable(false);
        }
    }//GEN-LAST:event_cantidadProductoKeyPressed

    private void distribCofarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distribCofarmaActionPerformed

    }//GEN-LAST:event_distribCofarmaActionPerformed

    private void chkSecundarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSecundarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSecundarioActionPerformed

    private void distribEmpsepharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distribEmpsepharActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_distribEmpsepharActionPerformed

    private void nombreMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMedicamentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        distribuidoresBtns.add(distribCofarma);
        distribuidoresBtns.add(distribEmpsephar);
        distribuidoresBtns.add(distribCemefar);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarCampos;
    private javax.swing.JTextField cantidadProducto;
    private javax.swing.JCheckBox chkPrincipal;
    private javax.swing.JCheckBox chkSecundario;
    private javax.swing.JButton confirmarPedido;
    private javax.swing.JRadioButton distribCemefar;
    private javax.swing.JRadioButton distribCofarma;
    private javax.swing.JRadioButton distribEmpsephar;
    private javax.swing.ButtonGroup distribuidoresBtns;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField nombreMedicamento;
    private javax.swing.JComboBox<String> tipoMedicamento;
    // End of variables declaration//GEN-END:variables
}
